version: '3.8'
services:
  discovery-server:
    build: ./discovery-server/discovery-server
    ports:
      - "8761:8761"
    restart: unless-stopped
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  api-gateway:
    build: ./api-gateway/api-gateway
    ports:
      - "9354:8080"
    restart: unless-stopped
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  user-service:
    build: ./user-service/user-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  order-service:
    build: ./order-service/order-service
    ports:
      - "9333:9333"
    restart: unless-stopped
    depends_on:
      - discovery-server
      - user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

